In [1]:
import numpy as np

In [3]:
print(np.__version__)

2.1.3


In [5]:
arr=np.array([1,2,3,4,5], ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]


In [6]:
print('number of dimensions: ',arr.ndim)

number of dimensions:  5


In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9,])
print(arr[1] +arr[8])
print(arr[1:4])

11
[2 3 4]


In [11]:
arr=np.array([[1,2,3,4,5,6],[9,8,7,6,5,8]])
print('2nd elemnts on the 1st row: ',arr[0,1])

2nd elemnts on the 1st row:  2


In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,4])
print(arr.dtype)

10
int64


In [16]:
arr = np.array([1.1, 2.1, 3.1])
newarr=arr.astype("i")# int,bool
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [17]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=40
print(arr)
print(x)

[40  2  3  4  5]
[1 2 3 4 5]


In [21]:
arr=np.array([1,2,3,4,5])
y=arr.view()
arr[2]=42
print (arr)
print(y)

[ 1  2 42  4  5]
[ 1  2 42  4  5]


In [22]:
arr=np.array([1,2,3,4,5])


x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [23]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [26]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array : ' ,arr.shape)

[[[[[1 2 3 4]]]]]
shape of array :  (1, 1, 1, 1, 4)


In [27]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
